name: Booking a session on Octiv (18:30)
on:
  schedule:
    - cron: "25 16 * * 1-5" # UTC is 3 hours behind Europe/Sofia; Check with Summer/Winter solstice
  workflow_dispatch: # Allow manual execution
jobs:
  Book-Session-One:
    runs-on: ubuntu-latest
    environment: gymbro secrets
    env:
      API_URL: ${{ vars.API_URL }}
      MYGYM_EMAIL: ${{ secrets.MYGYM_EMAIL }}
      MYGYM_PASS: ${{ secrets.MYGYM_PASS }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      LOCATION_ID: ${{ secrets.LOCATION_ID }}
      NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.16.0
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Book Session via script
        run: npm run book -- time=19:30 # Summer Solstice is 19:30; Winter Solstice is 18:30
