name: Testing Cron
on:
  schedule:
    - cron: "* * * * *"
      timezone: "Europe/Sofia"
  workflow_dispatch: # Allow manual execution
jobs:
  Book-Session-One:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.16.0
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test Job
        run: npm run test:job # Summer Time is 19:00; Winter Time is 18:00
